import {
  ShieldCheck, Truck, Zap, Award, Heart, Leaf, Sun, Flower2, HeadphonesIcon,
  Package, BadgeCheck, Clock, Gift, Star, Lock, Flame, Wifi, Battery, Cpu,
  Dumbbell, Sparkles, ThumbsUp, RotateCcw, Droplet, Brain, Moon,
  Search, ShoppingCart, CreditCard, Wallet, Smartphone, Mail, MapPin, Home,
  Store, Tag, Percent, BadgeDollarSign, Coins, Banknote, Pill, Apple, Salad,
  Scale, Gauge, Timer, Calendar, MapPinned, MessageCircle, Phone, Globe, Box,
  Boxes, PackageCheck, PackageOpen, ClipboardCheck, CircleCheck, Medal, Trophy,
  Target, TrendingUp, Activity, HeartPulse, Stethoscope, Cross, Vegan, Sprout,
  Waves, Thermometer, Snowflake, ShieldAlert, ScanBarcode, QrCode, Receipt,
  HandCoins, CircleDollarSign, RefreshCw, Undo2, Smile, Eye, Palette, Gem,
  Crown, Rocket, Megaphone, Bell, AlarmClock, Hourglass, Calculator, Ruler,
  Wrench, Settings, Plug, Cable, Monitor, Laptop, TabletSmartphone, Camera,
  Video, Bluetooth, Volume2, Lightbulb, CheckCircle2, CircleHelp, Info,
} from 'lucide-react';

/**
 * Catálogo de íconos que el comercio puede elegir para cada tarjeta de
 * "Beneficios" — un solo set genérico compartido por los 4 templates
 * rígidos (no uno distinto por template: simplifica el picker y alcanza
 * para cubrir fitness/beauty/tech/básico). Solo se guarda la clave
 * (ej. "shield") en LandingBeneficio.icono, nunca el componente.
 */
export const CATALOGO_ICONOS_BENEFICIOS = [
  { key: 'shield', label: 'Seguridad', Icon: ShieldCheck, keywords: 'proteccion seguro confianza' },
  { key: 'truck', label: 'Envío', Icon: Truck, keywords: 'delivery entrega transporte courier' },
  { key: 'zap', label: 'Rápido', Icon: Zap, keywords: 'velocidad energia inmediato express' },
  { key: 'award', label: 'Calidad', Icon: Award, keywords: 'premium certificado destacado' },
  { key: 'badge', label: 'Garantía', Icon: BadgeCheck, keywords: 'verificado respaldo certificado' },
  { key: 'heart', label: 'Cuidado', Icon: Heart, keywords: 'salud amor bienestar' },
  { key: 'leaf', label: 'Natural', Icon: Leaf, keywords: 'organico vegetal ingrediente planta' },
  { key: 'sun', label: 'Frescura', Icon: Sun, keywords: 'dia brillo vitamina energia' },
  { key: 'flower', label: 'Belleza', Icon: Flower2, keywords: 'beauty skincare piel cosmetica' },
  { key: 'headphones', label: 'Soporte', Icon: HeadphonesIcon, keywords: 'atencion ayuda asistencia' },
  { key: 'package', label: 'Producto', Icon: Package, keywords: 'paquete caja item' },
  { key: 'clock', label: 'Tiempo', Icon: Clock, keywords: 'hora plazo duracion' },
  { key: 'gift', label: 'Regalo', Icon: Gift, keywords: 'bonus obsequio gratis promo' },
  { key: 'star', label: 'Destacado', Icon: Star, keywords: 'favorito reseña rating' },
  { key: 'lock', label: 'Confianza', Icon: Lock, keywords: 'seguro privado pago' },
  { key: 'flame', label: 'Energía', Icon: Flame, keywords: 'fuego potencia intensidad' },
  { key: 'wifi', label: 'Conectividad', Icon: Wifi, keywords: 'internet señal online red' },
  { key: 'battery', label: 'Duración', Icon: Battery, keywords: 'bateria autonomia energia' },
  { key: 'cpu', label: 'Tecnología', Icon: Cpu, keywords: 'procesador chip electronica' },
  { key: 'dumbbell', label: 'Fitness', Icon: Dumbbell, keywords: 'gym entrenamiento fuerza musculo' },
  { key: 'sparkles', label: 'Especial', Icon: Sparkles, keywords: 'brillo nuevo magia destacado' },
  { key: 'thumbs-up', label: 'Satisfacción', Icon: ThumbsUp, keywords: 'aprobado recomendado like' },
  // Agregados para la ficha de producto de Fitness (ingredientes, cómo
  // funciona, garantías). Sirven igual en los otros templates: el catálogo
  // es uno solo y compartido.
  { key: 'rotate', label: 'Devolución', Icon: RotateCcw, keywords: 'cambio retorno reembolso' },
  { key: 'droplet', label: 'Absorción', Icon: Droplet, keywords: 'agua hidratacion liquido gota' },
  { key: 'brain', label: 'Enfoque', Icon: Brain, keywords: 'mente concentracion memoria' },
  { key: 'moon', label: 'Descanso', Icon: Moon, keywords: 'sueño noche relax dormir' },
  { key: 'search', label: 'Búsqueda', Icon: Search, keywords: 'buscar explorar encontrar filtro' },
  { key: 'cart', label: 'Carrito', Icon: ShoppingCart, keywords: 'comprar pedido tienda' },
  { key: 'card', label: 'Tarjeta', Icon: CreditCard, keywords: 'pago credito debito' },
  { key: 'wallet', label: 'Billetera', Icon: Wallet, keywords: 'pago dinero efectivo' },
  { key: 'cash', label: 'Efectivo', Icon: Banknote, keywords: 'dinero billete contra entrega' },
  { key: 'coins', label: 'Ahorro', Icon: Coins, keywords: 'monedas precio descuento plata' },
  { key: 'discount', label: 'Descuento', Icon: Percent, keywords: 'oferta rebaja promo porcentaje' },
  { key: 'price-tag', label: 'Precio', Icon: Tag, keywords: 'etiqueta oferta valor' },
  { key: 'dollar-badge', label: 'Buen precio', Icon: BadgeDollarSign, keywords: 'precio ahorro oferta' },
  { key: 'hand-coins', label: 'Pago fácil', Icon: HandCoins, keywords: 'pago efectivo ahorro dinero' },
  { key: 'money-circle', label: 'Valor', Icon: CircleDollarSign, keywords: 'precio dinero inversion' },
  { key: 'receipt', label: 'Comprobante', Icon: Receipt, keywords: 'factura ticket recibo' },
  { key: 'phone', label: 'Teléfono', Icon: Phone, keywords: 'llamada contacto' },
  { key: 'whatsapp', label: 'Mensaje', Icon: MessageCircle, keywords: 'chat whatsapp consulta contacto' },
  { key: 'mail', label: 'Email', Icon: Mail, keywords: 'correo contacto' },
  { key: 'smartphone', label: 'Celular', Icon: Smartphone, keywords: 'movil telefono app' },
  { key: 'location', label: 'Ubicación', Icon: MapPin, keywords: 'mapa direccion local' },
  { key: 'map', label: 'Mapa', Icon: MapPinned, keywords: 'ubicacion delivery zona' },
  { key: 'home', label: 'Hogar', Icon: Home, keywords: 'casa domicilio' },
  { key: 'store', label: 'Tienda', Icon: Store, keywords: 'local comercio negocio' },
  { key: 'globe', label: 'Online', Icon: Globe, keywords: 'web internet mundial' },
  { key: 'box', label: 'Caja', Icon: Box, keywords: 'paquete embalaje' },
  { key: 'boxes', label: 'Stock', Icon: Boxes, keywords: 'inventario cajas cantidad' },
  { key: 'package-check', label: 'Entrega segura', Icon: PackageCheck, keywords: 'envio recibido verificado' },
  { key: 'package-open', label: 'Contenido', Icon: PackageOpen, keywords: 'incluye caja abrir' },
  { key: 'checklist', label: 'Checklist', Icon: ClipboardCheck, keywords: 'lista control verificado' },
  { key: 'check', label: 'Correcto', Icon: CircleCheck, keywords: 'ok aprobado listo' },
  { key: 'medal', label: 'Premio', Icon: Medal, keywords: 'calidad ganador destacado' },
  { key: 'trophy', label: 'Más vendido', Icon: Trophy, keywords: 'top ganador bestseller' },
  { key: 'target', label: 'Objetivo', Icon: Target, keywords: 'meta resultado foco' },
  { key: 'growth', label: 'Crecimiento', Icon: TrendingUp, keywords: 'sube mejora resultado' },
  { key: 'activity', label: 'Actividad', Icon: Activity, keywords: 'pulso rendimiento salud' },
  { key: 'heart-pulse', label: 'Bienestar', Icon: HeartPulse, keywords: 'salud corazon cuidado' },
  { key: 'stethoscope', label: 'Asesoría salud', Icon: Stethoscope, keywords: 'medico consulta salud' },
  { key: 'cross', label: 'Salud', Icon: Cross, keywords: 'medical cuidado bienestar' },
  { key: 'pill', label: 'Suplemento', Icon: Pill, keywords: 'capsula vitamina pastilla' },
  { key: 'apple', label: 'Nutrición', Icon: Apple, keywords: 'fruta alimento dieta' },
  { key: 'salad', label: 'Alimentación', Icon: Salad, keywords: 'comida saludable dieta' },
  { key: 'scale', label: 'Control', Icon: Scale, keywords: 'peso balanza medida' },
  { key: 'gauge', label: 'Rendimiento', Icon: Gauge, keywords: 'velocidad potencia desempeño' },
  { key: 'vegan', label: 'Vegano', Icon: Vegan, keywords: 'vegetal natural planta' },
  { key: 'sprout', label: 'Origen vegetal', Icon: Sprout, keywords: 'planta natural organico' },
  { key: 'waves', label: 'Hidratación', Icon: Waves, keywords: 'agua liquido frescura' },
  { key: 'thermometer', label: 'Temperatura', Icon: Thermometer, keywords: 'frio calor control' },
  { key: 'snowflake', label: 'Frío', Icon: Snowflake, keywords: 'conservacion fresco congelado' },
  { key: 'timer', label: 'Timer', Icon: Timer, keywords: 'contador urgencia tiempo' },
  { key: 'calendar', label: 'Calendario', Icon: Calendar, keywords: 'fecha agenda dia' },
  { key: 'alarm', label: 'Alarma', Icon: AlarmClock, keywords: 'urgencia tiempo aviso' },
  { key: 'hourglass', label: 'Tiempo limitado', Icon: Hourglass, keywords: 'escasez espera contador' },
  { key: 'bell', label: 'Aviso', Icon: Bell, keywords: 'alerta notificacion' },
  { key: 'megaphone', label: 'Anuncio', Icon: Megaphone, keywords: 'promocion publicidad aviso' },
  { key: 'rocket', label: 'Impulso', Icon: Rocket, keywords: 'rapido lanzamiento crecimiento' },
  { key: 'crown', label: 'Premium', Icon: Crown, keywords: 'lujo mejor exclusivo' },
  { key: 'gem', label: 'Valor premium', Icon: Gem, keywords: 'joya calidad premium' },
  { key: 'palette', label: 'Diseño', Icon: Palette, keywords: 'color estilo beauty' },
  { key: 'eye', label: 'Vista', Icon: Eye, keywords: 'ver detalle mirar' },
  { key: 'smile', label: 'Experiencia', Icon: Smile, keywords: 'feliz satisfaccion usuario' },
  { key: 'shield-alert', label: 'Advertencia', Icon: ShieldAlert, keywords: 'seguridad alerta cuidado' },
  { key: 'barcode', label: 'Código', Icon: ScanBarcode, keywords: 'sku barra producto' },
  { key: 'qr', label: 'QR', Icon: QrCode, keywords: 'codigo escanear' },
  { key: 'refresh', label: 'Renovable', Icon: RefreshCw, keywords: 'actualizar repetir ciclo' },
  { key: 'undo', label: 'Cambio', Icon: Undo2, keywords: 'volver cambio devolucion' },
  { key: 'calculator', label: 'Cálculo', Icon: Calculator, keywords: 'precio cuota medida' },
  { key: 'ruler', label: 'Medidas', Icon: Ruler, keywords: 'dimension tamaño largo' },
  { key: 'wrench', label: 'Herramienta', Icon: Wrench, keywords: 'reparacion ajuste tecnico' },
  { key: 'settings', label: 'Configuración', Icon: Settings, keywords: 'ajuste opciones' },
  { key: 'plug', label: 'Energía eléctrica', Icon: Plug, keywords: 'enchufe corriente tecnologia' },
  { key: 'cable', label: 'Cable', Icon: Cable, keywords: 'conexion accesorio' },
  { key: 'monitor', label: 'Pantalla', Icon: Monitor, keywords: 'display tecnologia' },
  { key: 'laptop', label: 'Computadora', Icon: Laptop, keywords: 'notebook tecnologia' },
  { key: 'tablet-phone', label: 'Dispositivos', Icon: TabletSmartphone, keywords: 'celular tablet tecnologia' },
  { key: 'camera', label: 'Cámara', Icon: Camera, keywords: 'foto imagen' },
  { key: 'video', label: 'Video', Icon: Video, keywords: 'multimedia demostracion' },
  { key: 'bluetooth', label: 'Bluetooth', Icon: Bluetooth, keywords: 'inalambrico conexion' },
  { key: 'volume', label: 'Audio', Icon: Volume2, keywords: 'sonido parlante' },
  { key: 'lightbulb', label: 'Idea', Icon: Lightbulb, keywords: 'tip consejo solucion' },
  { key: 'circle-help', label: 'Ayuda', Icon: CircleHelp, keywords: 'pregunta faq duda' },
  { key: 'info', label: 'Información', Icon: Info, keywords: 'detalle dato' },
  { key: 'verified-check', label: 'Verificado', Icon: CheckCircle2, keywords: 'check aprobado certificado' },
];

const MAPA = new Map(CATALOGO_ICONOS_BENEFICIOS.map(i => [i.key, i.Icon]));
const DEFAULT_ICON = ShieldCheck;

/** clave guardada → componente de ícono. Clave null/no reconocida = ícono genérico. */
export function getIconoBeneficio(key) {
  return MAPA.get(key) || DEFAULT_ICON;
}
