name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code and Deploy
        run: |
          cd ~/gesicomm/gesicomm-frontend
          git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Gesicomm/gesicomm-frontend.git main
          cd ~/gesicomm
          docker compose up -d --build frontend
